apps/eplace/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('',
    url(r'^index/$', 'eplace.views.index', name="eplace_index"),
    (r'^teacher/', include('eplace.urls_teacher')),
    (r'^student/', include('eplace.urls_student')),
    (r'^groups/', include('eplace.urls_groups')),
    (r'^settings/', include('eplace.urls_settings')),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    (r'^', include('eplace.urls')),
    (r'^geturl/', 'common.views.get_url'),
    (r'^admin/', include(admin.site.urls)),
    (r'^robots\.txt', 'robots.views.rules_list'),
#    (r'^accounts/', include('invitation.urls')),
    (r'^accounts/', include('registration.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
#    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True} ),
    )

apps/eplace/models.py
from django.db import models
from django.contrib.auth.models import User, Group as UserGroup
from django.conf import settings

import datetime, logging

log = logging.getLogger('eplace')

class Subject(models.Model):
    short_name      = models.CharField(max_length=10)
    full_name       = models.CharField(max_length=100)
    
    def __unicode__(self):
        return u'{0}'.format(self.full_name)

class Faculty(models.Model):
    title           = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = 'faculty'
        verbose_name_plural = 'faculties'
    
    def __unicode__(self):
        return self.title
    
class Group(models.Model):
    faculty         = models.ForeignKey(Faculty)
    title           = models.CharField(max_length=10)
    start_year      = models.IntegerField()
#    faculty         = models.CharField(max_length=50)

    class Meta:
        ordering = ('faculty', '-start_year', 'title')

#    @property
    def course(self):
        date = datetime.datetime.today().date()
        year = date.year
        if (date.month < 9):
            year-=1
        return year - self.start_year+ 1
        

    def __unicode__(self):
        return '{0} {1} course'.format(self.title, self.course())

class Student(models.Model):
    group           = models.ForeignKey(Group, blank=True, null=True)
    name            = models.CharField(max_length=50, blank=True)
    email           = models.EmailField(null=True, blank=True)
    info            = models.TextField(null=True, blank=True)
    
    @property
    def start_year(self):
        return self.group.start_year
    
    def __unicode__(self):
        return '{0}'.format(self.name)
    
    def fromString(self, line):
        t = line.split(';')
        n = len(t)
        if n > 0:
            self.name = t[0].strip()
        if n > 1:
            self.email = t[1].strip()
        if n > 2:
            self.info = t[2].strip()
#        if n > 3:
#            self.info = t[3].strip()
            
    
    @models.permalink
    def link(self):
        return ('eplace_students_student',None, {'id': self.pk})
    
    def subjects(self):
        return self.lessonday_set.only('subject').distinct('subject')
    
    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'group',)      

#====================================================

class Dean(models.Model):
    user            = models.OneToOneField(User)
    faculty         = models.ForeignKey(Faculty)
    
    class Meta:
        unique_together = ('user','faculty')
        
    def get_name(self):
        return self.user.username

        
    def __unicode__(self):
        return '{0}'.format(self.get_name())
    
class Teacher(models.Model):
    user            = models.OneToOneField(User)
    
    def get_name(self):
        return self.user.username

    def __unicode__(self):
        return '{0}'.format(self.get_name())
    
class Superviser(models.Model):
    user            = models.OneToOneField(User)
    groups          = models.ManyToManyField(Group, null=True, blank=True)
    
    def get_name(self):
        return self.user.username

    def __unicode__(self):
        return '{0}'.format(self.get_name())

#===========================================================    

class Lesson(models.Model):
    teacher         = models.ForeignKey(Teacher)
    subject         = models.ForeignKey(Subject)
    groups          = models.ManyToManyField(Group)
    hours           = models.IntegerField(default=1)
    week_days       = models.CharField(max_length=30, default='')
    type            = models.CharField(max_length=15, default='')
    
    def short_name(self):
        return self.subject.short_name
    
    @models.permalink
    def link(self):
        return ('eplace_students_lesson', None, {'id': self.pk})
    
    
    def __unicode__(self):
        if self.type != '':
            return u'{0} {1} {2}'.format(self.teacher, self.subject, self.type)
        else:
            return u'{0} {1}'.format(self.teacher, self.subject)
        

class LessonDay(models.Model):
    lesson          = models.ForeignKey(Lesson)
    date            = models.DateField()
    
    class Meta:
        unique_together = ('date', 'lesson')
        ordering = ('date',)
        
    
    def is_absent(self, student):
        ticks = Tick.objects.filter(ld=self, student=student)
        n = ticks.count()
        if n > 0:
            tick = ticks[0]
            if tick.value == 0:
                return True
        return False
                    

    @models.permalink
    def del_link(self):
        return ('eplace_teacher_ld_delete', None, {'lid' : self.pk})
    
    def __unicode__(self):
        return '{0} {1} {2}'.format(self.teacher, self.subject, self.group)
    
class Tick(models.Model):
    ld              = models.ForeignKey(LessonDay)
    student         = models.ForeignKey(Student)
    value           = models.IntegerField()
    pub_date        = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-pub_date',)
    
class GenerateLessonDay(models.Model):
    lesson          = models.ForeignKey(Lesson)
    start_date      = models.DateField()
    end_date        = models.DateField()
    weak_days       = models.CharField(max_length=50, help_text="Separate lesson-days using comma (,). <br>Ex: mon, wed<br>Weekdays are defined by: mon, tue, wed, thu, fri, sat, sun")
    
    def save(self, *a, **kw):
        super(GenerateLessonDay, self).save(*a,**kw)
        #TODO: generate here
        t = self.weak_days.replace(' ','').split(',')
        d = {}
        for x in t:
            k = ['mon','tue','wed','thu','fri','sat','sun'].index(x)
            d.update({k:self.lesson.hours})
        
        cur = self.start_date
        while cur < self.end_date:
            w = cur.weekday()
            if d.has_key(w):
                o, c = LessonDay.objects.get_or_create(
                     lesson=self.lesson,
                     date=cur
                )
                o.save()
            cur = cur.fromtimestamp(int(cur.strftime("%s"))+24*60*60)
        super(GenerateLessonDay, self).delete(*a,**kw)



class EplaceUser(User):
    
    class Meta:
        proxy = True

    def is_teacher(self):
        try:
            Teacher.objects.get(user=self)
            return True
        except Teacher.DoesNotExist:
            return False
        
    def is_superviser(self):
        try:
            Superviser.objects.get(user=self)
            return True
        except Superviser.DoesNotExist:
            return False
        
    def make_teacher(self):
        Teacher.objects.get_or_create(user=self)

    def make_superviser(self):
        Superviser.objects.get_or_create(user=self)
        
        
class CopyPasteStudents(models.Model):
    group           = models.ForeignKey(Group)
    text            = models.TextField()
    
    def save(self, *a, **kw):
        super(CopyPasteStudents, self).save(*a,**kw)
        list = self.text.split('\n')
        for line in list:
            if line == '':
                continue
            s = Student(group=self.group)
            s.fromString(line)
            try:
                ns = Student.objects.get(name=s.name)
            except Student.DoesNotExist:
                s.save()                
        super(CopyPasteStudents, self).delete(*a,**kw)

apps/eplace/forms.py
from django import forms
from django.conf import settings

from eplace.models import Group, Subject, LessonDay, GenerateLessonDay, Lesson,\
    Student, CopyPasteStudents
from common.models import UserField

import logging, traceback

log = logging.getLogger('eplace') 

class TickForm(forms.Form):
    teacher = None 
    
    def __init__(self, teacher, *a, **kw):
        super(TickForm, self).__init__(*a, **kw)
        self.teacher = teacher
        self.fields['lesson'].queryset = teacher.lesson_set.all()
        
    lesson = forms.ModelChoiceField(queryset=Lesson.objects.none())
    tick    = forms.CharField()

class LessonDayForm(forms.ModelForm):
    
    class Meta:
        model = LessonDay
        exclude = ['lesson']
        
    def save(self, lesson): 
        o,c = LessonDay.objects.get_or_create(lesson=lesson, date=self.cleaned_data.get("date"))
        o.save()
        return o
    
class GenerateLessonDayForm(forms.ModelForm):

    class Meta:
        model = GenerateLessonDay
        exclude = ['lesson']
        
    def clean_weak_days(self):
        weak_days = self.cleaned_data.get('weak_days')
        t = weak_days.replace(' ','').split(',')
        for x in t:
            if x not in ('mon','tue','wed','thu','fri','sat','sun'):
                raise forms.ValidationError("weak-day wrongly specified")
        return weak_days

    def save(self, lesson): 
        o = GenerateLessonDay(
            lesson = lesson,
            start_date=self.cleaned_data.get("start_date"),
            end_date=self.cleaned_data.get("end_date"),
            weak_days=self.cleaned_data.get("weak_days"),
        )
        o.save()
        
class CopyPasteStudentsForm(forms.ModelForm):
    
    class Meta:
        model = CopyPasteStudents
        
    def clean_text(self):
        text = self.cleaned_data.get("text")
        list = text.split('\n')
        for line in list:
            if line == '':
                continue
            s = Student()                
            s.fromString(line)
#            log.debug(s.name)
            try:                
                ns = Student.objects.get(name=s.name)
                error = forms.ValidationError("Student {0} already exist. He is in group {1}".format(s.name, ns.group))
                self.fields['text'].error = error
#                log.debug('raise error')
                raise error 
            except Student.DoesNotExist:
                pass
#                log.debug("{0} not found".format(s.name))
        return text
        
        
        
class SettingsForm(forms.Form):
    absence_percentage_limit = forms.IntegerField()
    
    def save(self, user, *a, **kw):
        o,c = UserField.objects.get_or_create(user=user, key="absence_percentage_limit")
        o.value = self.cleaned_data.get('absence_percentage_limit', settings.ABSENCE_PERCENTAGE_LIMIT)
        o.save()
        
        
def get_default_settings(request):
    try:
        o = UserField.objects.get(user=request.user, key="absence_percentage_limit")
        return {'absence_percentage_limit': o.value}
    except UserField.DoesNotExist:
        return {'absence_percentage_limit':settings.ABSENCE_PERCENTAGE_LIMIT}

apps/eplace/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def index(request, template_name="eplace/home.html"):
    c = RequestContext(request, {})
    return render_to_response(template_name, c)

apps/eplace/templates/eplace/teacher/index.html
{% extends "eplace/base.html" %}

{% block jsblock %}
{{ block.super }}
<link rel="stylesheet" href="{{MEDIA_URL}}static_media/jscss/dateinput.css" type="text/css" />
<script>
{% include "eplace/teacher/teacher.js" %}
	$(document).ready(function(){
		$('div.w-subject').find('a').click(function(){
			if ($(this).hasClass('selected')){
				teacher.lessons.deselect(this);
			}else{
				teacher.lessons.deselectAll();
				teacher.lessons.select(this);
			}
		});
	});
</script>
{% endblock %}

{% block content %}
<div class="widget-container">
<div>
<!-- 
	<div class="fr widget w-group">
	<h2>Groups</h2>
	{% with teacher.groups.all as object_list %}
	{% for object in object_list %}
	<a rel="{{ object.pk }}">{{ object }}</a>
	{% endfor %}
	{% endwith %}
	</div>
 -->	
	<div class="widget w-subject">
	<h2>Lessons</h2>
	{% with teacher.lesson_set.all as object_list %}
	{% for object in object_list %}
	<a rel="{{ object.pk }}">{{ object.subject }} {{ object.type}}<br>
	<tt>{% for group in object.groups.all %}{{group}}{% if not forloop.last %}, {% endif %}{% endfor %}</tt>
	</a>
	{% endfor %}
	{% endwith %}
	</div>
	<div class="clear"></div>
</div>
<div class="hidden w-loading"><img src="{{MEDIA_URL}}static_media/images/upload.gif"/></div>
<div class="widget w-table">
</div>
<div class="widget">
<a onClick="teacher.reset();">Reset</a> | <a onClick="teacher.save();">Save</a> | 
<a id="add-ld-trigger" onclick="teacher.openALDOverlay();">Add lesson-day</a> | <a id="gen-ld-trigger" onclick="teacher.openGLDOverlay();">Generate lesson-days</a> 
</div>
</div>
{% endblock %}

apps/eplace/templates/eplace/teacher/settings.html
{% extends "eplace/base.html" %}

{% block jsblock %}
{{ block.super }}
<link rel="stylesheet" href="{{MEDIA_URL}}static_media/jscss/dateinput.css" type="text/css" />
<script>
{% include "eplace/teacher/teacher_settings.js" %}
	$(document).ready(function(){
	});
</script>
{% endblock %}

{% block content %}
<div class="widget-container">
<div class="hidden w-loading"><img src="{{MEDIA_URL}}static_media/images/upload.gif"/></div>
<div class="widget w-table">
{% include "eplace/teacher/settings_form.html" %}
</div>
<div class="widget">
<a onClick="teacher.reset();" rel="{% url eplace_settings_get %}">Reset</a> | <a onClick="teacher.save();" rel="{% url eplace_settings_save %}">Save</a> 
</div>
</div>
{% endblock %}

apps/eplace/templates/eplace/teacher/settings_form.html
{% load uni_form %}
<h2>Settings</h2>
<form id="settings-form" method="POST" action="{% url eplace_settings_save %}">
{{ form|as_uni_form }}
</form>

apps/eplace/templates/eplace/teacher/subject.html
{% load eplace_tags uni_form %}
<table class="group-table" cellpadding="0" cellspacing="0">
<tr>
	<th>Name</th>
	{% for l in lessons %}
	<th title="Lesson is on {{ l.date|date:"d b Y" }} for {{ lesson.hours }} hours">{{ l.date|date:"d" }}</th>
	{% endfor %}
</tr>
<tr>
<td></td>
	{% for l in lessons %}
<td><a id="ap-handle" rel="tick-{{ l.pk }}" onClick="return false;" title="{{_("all present")}}">
	<img src="{{MEDIA_URL}}static_media/images/bullet_add.png" height=16 width=16 />
	</a></td>
	{% endfor %}

</tr>
{% for group in lesson.groups.all %}
{% with group.student_set.all as object_list %}
{% for object in object_list %}
<tr>
	<td><a href="{{ object.link }}" title="Group: {{group}}">{{ object }}</a></td>
	{% for l in lessons %}
	<td class="tick" id="tick-{{ l.pk }}" title="{{ object }} {{ group }}
	{% with l|get_tick:object as tick %}{% if tick %}Ticked on {{ tick.pub_date|date:"d b Y" }}.{% endif%}{% endwith %}" rel="{{ l.pk }}:{{ object.pk }}">{{ l|get_tick_display:object }}</td>
	{% endfor %}
</tr>
{% endfor %}
{% endwith %}
{% endfor %}
<tr>
	<td></td>
	{% for l in lessons %}
	<td><a href="{{ l.del_link }}" id="del-lesson-day" onClick="return false;" title="Delete lesson day">
	<img src="{{MEDIA_URL}}static_media/images/bullet_delete.png" height=16 width=16 />
	</a></td>
	{% endfor %}
</tr>
</table>

<div class="hidden">
<form method="post" action="{% url eplace_teacher_tick_save %}" id="tick-form">
{% csrf_token %}
<input type='text' name="lesson" value="{{ lesson.pk }}">
<input type='text' id="tick0" name="tick" value="12">
</form>
</div>

<div id="lesson-day-form" class="hidden popup">
<form method="post" action="{% url eplace_teacher_lesson lid=lesson.pk %}">
{% csrf_token %}
{{ lesson_form|as_uni_form }}
<input type="button" onClick="teacher.addLD();" value="add" />
<input type="button" onClick="teacher.ldApi.overlay().close();" value="cancel"/>
<br/>
<tt>Press Esc to close.</tt>
</form>
</div>

<div id="generate-lesson-day-form" class="hidden popup">
<form method="post" action="{% url eplace_teacher_generate_ld lid=lesson.pk %}">
{% csrf_token %}
{{ glf_form|as_uni_form }}
<input type="button" onClick="teacher.genLD();" value="generate" />
<input type="button" onClick="teacher.gldApi.overlay().close();" value="cancel"/>
<br/>
<tt>Press Esc to close.</tt>
</form>
</div>